/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawImg(CTRPluginFramework::Icon *this, unsigned __int8 *a2, int a3, int a4, int a5, int a6);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawAbout(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCapsLockOn(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCentreOfGravity(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCheckBox(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawClearSymbol(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawClipboard(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawClose(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawController(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCut(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawDuplicate(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawEdit(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawEnterKey(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFolder(int a1, int a2);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFolder(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawAddFavorite(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFavorite(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFile(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawGameController(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawGrid(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawInfo(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawGuide(CTRPluginFramework::Icon *this, int a2, int a3);
int __fastcall CTRPluginFramework::Icon::DrawHandCursor(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawHappyFace(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawKeyboard(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawMore(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawPlus(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawRAM(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawRestart(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawRocket(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawSave(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawSearch(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawSettings(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawShutdown(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawTools(CTRPluginFramework::Icon *this, int a2, int a3);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawTrash(CTRPluginFramework::Icon *this, int a2, int a3, bool a4);
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawUnsplash(CTRPluginFramework::Icon *this, int a2, int a3);
// int threadGetCurrent(void); weak
// _DWORD __cdecl CTRPluginFramework::ScreenImpl::GetLeftFramebuffer(CTRPluginFramework::ScreenImpl *__hidden this, int, int); idb
// int __fastcall CTRPluginFramework::ScreenImpl::GetFramebufferInfos(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall ZTHN18CTRPluginFramework9PrivColor15FromFramebufferE(_DWORD); weak
// int __fastcall CTRPluginFramework::Color::Blend(_DWORD, _DWORD, _DWORD); weak
// int ZTHN18CTRPluginFramework9PrivColor13ToFramebufferE(void); weak
// _DWORD CTRPluginFramework::ScreenImpl::Is3DEnabled(CTRPluginFramework::ScreenImpl *__hidden this); idb
// _DWORD __cdecl CTRPluginFramework::ScreenImpl::GetRightFramebuffer(CTRPluginFramework::ScreenImpl *__hidden this, int, int); idb

//-------------------------------------------------------------------------
// Data declarations

// extern __thread _UNKNOWN CTRPluginFramework::PrivColor::FromFramebuffer; weak
// extern __thread _UNKNOWN CTRPluginFramework::PrivColor::ToFramebuffer; weak
// extern _UNKNOWN CTRPluginFramework::Renderer::hookContext; weak
// extern _UNKNOWN CTRPluginFramework::ScreenImpl::Top; weak
// extern _UNKNOWN CTRPluginFramework::ScreenImpl::Bottom; weak
// extern _UNKNOWN About15; weak
// extern _UNKNOWN CapsLockOnFilled15; weak
// extern _UNKNOWN CapsLockOn15; weak
// extern _UNKNOWN CentreofGravity15; weak
// extern _UNKNOWN CheckedCheckbox; weak
// extern _UNKNOWN UnCheckedCheckbox; weak
// extern _UNKNOWN ClearSymbolFilled15; weak
// extern _UNKNOWN ClearSymbol15; weak
// extern _UNKNOWN ClipboardFilled25; weak
// extern _UNKNOWN Clipboard25; weak
// extern _UNKNOWN CloseWindowFilled20; weak
// extern _UNKNOWN CloseWindow20; weak
// extern _UNKNOWN Controller15; weak
// extern _UNKNOWN CutFilled25; weak
// extern _UNKNOWN Cut25; weak
// extern _UNKNOWN DuplicateFilled25; weak
// extern _UNKNOWN Duplicate25; weak
// extern _UNKNOWN EditFilled25; weak
// extern _UNKNOWN Edit25; weak
// extern _UNKNOWN EnterKeyFilled15; weak
// extern _UNKNOWN EnterKey15; weak
// extern _UNKNOWN FolderFilled; weak
// extern _UNKNOWN AddFavoriteFilled25; weak
// extern _UNKNOWN AddFavorite25; weak
// extern _UNKNOWN Star15; weak
// extern _UNKNOWN File15; weak
// extern _UNKNOWN GameControllerFilled25; weak
// extern _UNKNOWN GameController25; weak
// extern _UNKNOWN Grid15; weak
// extern _UNKNOWN InfoFilled25; weak
// extern _UNKNOWN Info25; weak
// extern _UNKNOWN UserManualFilled15; weak
// extern _UNKNOWN HandCursor15; weak
// extern _UNKNOWN HappyFilled15; weak
// extern _UNKNOWN Happy15; weak
// extern _UNKNOWN KeyboardFilled25; weak
// extern _UNKNOWN Keyboard25; weak
// extern _UNKNOWN More15; weak
// extern _UNKNOWN PlusFilled25; weak
// extern _UNKNOWN Plus25; weak
// extern _UNKNOWN RAM15; weak
// extern _UNKNOWN Restart15; weak
// extern _UNKNOWN Rocket40; weak
// extern _UNKNOWN Save25; weak
// extern _UNKNOWN Search15; weak
// extern _UNKNOWN Settings15; weak
// extern _UNKNOWN Shutdown15; weak
// extern _UNKNOWN Maintenance15; weak
// extern _UNKNOWN TrashFilled25; weak
// extern _UNKNOWN Trash25; weak
// extern _UNKNOWN Unsplash15; weak


//----- (00000004) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawImg(CTRPluginFramework::Icon *this, unsigned __int8 *a2, int a3, int a4, int a5, int a6)
{
  int v6; // r6
  unsigned __int8 *v7; // r4
  int v8; // r0
  bool v9; // zf
  unsigned __int8 *v10; // r0
  int v11; // r6
  CTRPluginFramework::ScreenImpl **v12; // r5
  int v13; // r7
  int v14; // r0
  int v15; // r8
  CTRPluginFramework::Icon *v16; // r10
  int v17; // r11
  int v18; // r5
  int v19; // r9
  unsigned int v20; // r2
  char v21; // r1
  bool v22; // cf
  bool v23; // zf
  int v24; // r3
  int v26; // [sp+0h] [bp-58h]
  int v27; // [sp+4h] [bp-54h]
  int v28; // [sp+8h] [bp-50h]
  int v29; // [sp+Ch] [bp-4Ch]
  CTRPluginFramework::Icon *v30; // [sp+14h] [bp-44h]
  char v31; // [sp+1Bh] [bp-3Dh]
  int v32; // [sp+1Ch] [bp-3Ch]
  unsigned int v33; // [sp+20h] [bp-38h]
  int v34; // [sp+24h] [bp-34h]
  int v35; // [sp+28h] [bp-30h]
  int v36; // [sp+2Ch] [bp-2Ch]

  v6 = a3;
  v28 = a4;
  v30 = this;
  v7 = a2;
  v8 = threadGetCurrent();
  v9 = v8 == 0;
  if ( v8 )
    v10 = (unsigned __int8 *)(v8 + 1136);
  else
    v10 = (unsigned __int8 *)&CTRPluginFramework::Renderer::hookContext;
  if ( !v9 )
    v10 += 12;
  v26 = *v10;
  v34 = -16777216;
  v11 = v6 + a5;
  if ( v26 )
  {
    if ( v26 != 1 )
      return v7;
    v12 = (CTRPluginFramework::ScreenImpl **)&CTRPluginFramework::ScreenImpl::Top;
  }
  else
  {
    v12 = (CTRPluginFramework::ScreenImpl **)&CTRPluginFramework::ScreenImpl::Bottom;
  }
  v13 = CTRPluginFramework::ScreenImpl::GetLeftFramebuffer(*v12, (int)v7, v11);
  v14 = CTRPluginFramework::ScreenImpl::GetFramebufferInfos(*v12, &v32, &v33, &v31);
  LOBYTE(v27) = 0;
  v29 = __mrc(15, 0, 13, 0, 3);
  while ( v13 )
  {
    v15 = 0;
    v16 = v30;
    while ( v15 < v28 )
    {
      v17 = 0;
      v18 = (int)v16 + 4;
      v19 = v13 + v32 * v15;
      while ( a5 > v17 )
      {
        v20 = *(unsigned __int8 *)(v18 - 4);
        LOBYTE(v34) = *(_BYTE *)(v18 - 1);
        v21 = *(_BYTE *)(v18 - 2);
        v22 = v20 >= 0x19;
        v23 = v20 == 25;
        HIBYTE(v34) = v20;
        BYTE1(v34) = v21;
        if ( v20 <= 0x19 )
          v20 = v33;
        if ( v23 || !v22 )
          v19 += v20;
        BYTE2(v34) = *(_BYTE *)(v18 - 3);
        if ( !v23 && v22 )
        {
          if ( &ZTHN18CTRPluginFramework9PrivColor15FromFramebufferE )
            ZTHN18CTRPluginFramework9PrivColor15FromFramebufferE(v14);
          v35 = (*(int (__fastcall **)(int))((char *)&CTRPluginFramework::PrivColor::FromFramebuffer + v29))(v19);
          v36 = CTRPluginFramework::Color::Blend(&v35, &v34, 0);
          if ( &ZTHN18CTRPluginFramework9PrivColor13ToFramebufferE )
            ZTHN18CTRPluginFramework9PrivColor13ToFramebufferE();
          v14 = (*(int (__fastcall **)(int, int *))((char *)&CTRPluginFramework::PrivColor::ToFramebuffer + v29))(
                  v19,
                  &v36);
          v19 = v14;
        }
        ++v17;
        v18 += 4;
      }
      ++v15;
      v16 = (CTRPluginFramework::Icon *)((char *)v16 + 4 * (a5 & ~(a5 >> 31)));
    }
    if ( v26 == 1 )
      v24 = ((unsigned __int8)v27 ^ 1) & 1;
    else
      v24 = 0;
    if ( !v24 || (v27 = CTRPluginFramework::ScreenImpl::Is3DEnabled(CTRPluginFramework::ScreenImpl::Top)) == 0 )
    {
      v7 += v28;
      return v7;
    }
    v14 = CTRPluginFramework::ScreenImpl::GetRightFramebuffer(CTRPluginFramework::ScreenImpl::Top, (int)v7, v11);
    v13 = v14;
  }
  return v7;
}
// 960: using guessed type int threadGetCurrent(void);
// 968: using guessed type int __fastcall CTRPluginFramework::ScreenImpl::GetFramebufferInfos(_DWORD, _DWORD, _DWORD, _DWORD);
// 96C: using guessed type int __fastcall ZTHN18CTRPluginFramework9PrivColor15FromFramebufferE(_DWORD);
// 970: using guessed type int __fastcall CTRPluginFramework::Color::Blend(_DWORD, _DWORD, _DWORD);
// 974: using guessed type int ZTHN18CTRPluginFramework9PrivColor13ToFramebufferE(void);

//----- (00000224) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawAbout(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(About15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000250) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCapsLockOn(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&CapsLockOnFilled15;
  else
    v4 = (CTRPluginFramework::Icon **)&CapsLockOn15;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (0000028C) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCentreOfGravity(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(CentreofGravity15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000002B8) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCheckBox(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&CheckedCheckbox;
  else
    v4 = (CTRPluginFramework::Icon **)&UnCheckedCheckbox;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000002F4) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawClearSymbol(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&ClearSymbolFilled15;
  else
    v4 = (CTRPluginFramework::Icon **)&ClearSymbol15;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000330) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawClipboard(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&ClipboardFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Clipboard25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (0000036C) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawClose(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&CloseWindowFilled20;
  else
    v4 = (CTRPluginFramework::Icon **)&CloseWindow20;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 20, 20, a2);
}

//----- (000003A8) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawController(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Controller15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000003D4) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawCut(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&CutFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Cut25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000410) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawDuplicate(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&DuplicateFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Duplicate25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (0000044C) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawEdit(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&EditFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Edit25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000488) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawEnterKey(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&EnterKeyFilled15;
  else
    v4 = (CTRPluginFramework::Icon **)&EnterKey15;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000004C4) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFolder(int a1, int a2)
{
  return CTRPluginFramework::Icon::DrawImg(FolderFilled, *(unsigned __int8 **)a1, *(_DWORD *)(a1 + 4), 15, 15, a2);
}

//----- (000004EC) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFolder(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(FolderFilled, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000518) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawAddFavorite(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&AddFavoriteFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&AddFavorite25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000554) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFavorite(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Star15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000580) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawFile(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(File15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000005AC) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawGameController(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&GameControllerFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&GameController25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (000005E8) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawGrid(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Grid15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000614) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawInfo(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&InfoFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Info25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000650) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawGuide(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(UserManualFilled15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (0000067C) --------------------------------------------------------
int __fastcall CTRPluginFramework::Icon::DrawHandCursor(CTRPluginFramework::Icon *this, int a2, int a3)
{
  CTRPluginFramework::Icon *v3; // r4

  v3 = this;
  CTRPluginFramework::Icon::DrawImg(HandCursor15, (unsigned __int8 *)this, a2, 15, 15, a2);
  return (int)v3 + 15;
}

//----- (000006B0) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawHappyFace(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&HappyFilled15;
  else
    v4 = (CTRPluginFramework::Icon **)&Happy15;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000006EC) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawKeyboard(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&KeyboardFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Keyboard25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000728) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawMore(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(More15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000754) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawPlus(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&PlusFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Plus25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000790) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawRAM(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(RAM15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000007BC) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawRestart(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Restart15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000007E8) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawRocket(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Rocket40, (unsigned __int8 *)this, a2, 40, 40, a2);
}

//----- (00000814) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawSave(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Save25, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (00000840) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawSearch(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Search15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (0000086C) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawSettings(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Settings15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (00000898) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawShutdown(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Shutdown15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000008C4) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawTools(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Maintenance15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

//----- (000008F0) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawTrash(CTRPluginFramework::Icon *this, int a2, int a3, bool a4)
{
  CTRPluginFramework::Icon **v4; // r3

  if ( a3 )
    v4 = (CTRPluginFramework::Icon **)&TrashFilled25;
  else
    v4 = (CTRPluginFramework::Icon **)&Trash25;
  return CTRPluginFramework::Icon::DrawImg(*v4, (unsigned __int8 *)this, a2, 25, 25, a2);
}

//----- (0000092C) --------------------------------------------------------
unsigned __int8 *__fastcall CTRPluginFramework::Icon::DrawUnsplash(CTRPluginFramework::Icon *this, int a2, int a3)
{
  return CTRPluginFramework::Icon::DrawImg(Unsplash15, (unsigned __int8 *)this, a2, 15, 15, a2);
}

// ALL OK, 37 function(s) have been successfully decompiled
